const projects = [
  {
    id: 'project3',
    title: '示例作品 03',
    img: '/project3/project3.webp',
    link: '/projects/project3',
    date: '2023',
    liveLink: 'https://www.example.com/',
    company: '请在作品管理器中替换',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/7.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/6.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/video2.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/5.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/8.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      '这是原项目自带的示例作品。请打开作品管理器，点击编辑，替换标题、介绍、封面和详情图片。',
    ],
  },
  {
    id: 'project4',
    title: '示例作品 04',
    img: '/project4/project4.webp',
    link: '/projects/project4',
    date: '2024',
    company: '请在作品管理器中替换',
    liveLink: undefined,
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/project4/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/2.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/5.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/6.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/11.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      '这是原项目自带的示例作品。请打开作品管理器，点击编辑，替换标题、介绍、封面和详情图片。',
    ],
  },
  {
    id: 'project5',
    title: '示例作品 05',
    img: '/project5/project5.webp',
    link: '/projects/project5',
    date: '2024',
    company: '请在作品管理器中替换',
    liveLink: undefined,
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/project5/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/4.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/10.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      '这是原项目自带的示例作品。请打开作品管理器，点击编辑，替换标题、介绍、封面和详情图片。',
    ],
  },
  {
    id: 'project1',
    title: '示例作品 01',
    img: '/project1/project1.webp',
    link: '/projects/project1',
    date: '2024',
    company: '请在作品管理器中替换',
    livelink: undefined,
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/7.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/3.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      '这是原项目自带的示例作品。请打开作品管理器，点击编辑，替换标题、介绍、封面和详情图片。',
    ],
  },
  {
    id: 'project2',
    title: '示例作品 02',
    img: '/project2/project2.webp',
    link: '/projects/project2',
    date: '2022',
    company: '请在作品管理器中替换',
    liveLink: 'https://www.example.com/',
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project2/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      '这是原项目自带的示例作品。请打开作品管理器，点击编辑，替换标题、介绍、封面和详情图片。',
    ],
  },
];
export default projects;
